#!/usr/bin/env bash
#
# Henrycraft verification checks.
#
#   bash tools/check.sh              run every check
#   bash tools/check.sh --static     skip the two that need an Android build
#
# Checks 2 and 6 need ./gradlew :app:assembleDebug to have produced output, so
# they need the Android SDK. Without it they report SKIP and the script exits
# non-zero, because a skipped check is not a passing one.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
ROOT=$(pwd)

STATIC_ONLY=0
[[ "${1:-}" == "--static" ]] && STATIC_ONLY=1

pass=0 fail=0 skip=0

ok()   { printf '  \033[32mPASS\033[0m  %s\n' "$1"; pass=$((pass+1)); }
bad()  { printf '  \033[31mFAIL\033[0m  %s\n' "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; fail=$((fail+1)); }
meh()  { printf '  \033[33mSKIP\033[0m  %s\n' "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; skip=$((skip+1)); }

# Both files below deliberately *document* the things these checks look for -
# the manifest explains the missing INTERNET permission, the Activity explains
# why file:// is not used. Grepping the raw text would match that prose, so
# comments are stripped first and only real code is inspected.
strip_xml_comments() {
  python3 - "$1" <<'PY'
import re, sys
src = open(sys.argv[1], encoding='utf-8').read()
sys.stdout.write(re.sub(r'<!--.*?-->', '', src, flags=re.S))
PY
}

strip_kt_comments() {
  python3 - "$1" <<'PY'
import re, sys
src = open(sys.argv[1], encoding='utf-8').read()
src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)   # block comments and KDoc
src = re.sub(r'(?<!:)//[^\n]*', '', src)          # line comments, but not "https://"
sys.stdout.write(src)
PY
}

APK=android/app/build/outputs/apk/debug/app-debug.apk
ASSET=android/app/src/main/assets/index.html
MANIFEST=android/app/src/main/AndroidManifest.xml
ACTIVITY=android/app/src/main/java/com/flashtech/henrycraft/MainActivity.kt

echo "Henrycraft checks  ($ROOT)"
echo

# --- 1 -----------------------------------------------------------------------
# No external URLs in the page. three.js legitimately contains
# http://www.w3.org/1999/xhtml as the createElementNS namespace, which is not a
# network request, so it is excluded rather than removed.
echo "1. index.html has no external URLs"
urls=$(grep -oE 'https?://[^"'"'"' <>)]+' index.html | grep -v 'www\.w3\.org' | sort -u)
if [[ -z "$urls" ]]; then
  ok "no external URLs (only the w3.org XML namespace remains)"
else
  bad "external URLs found" "$(echo "$urls" | tr '\n' ' ')"
fi

# --- 2 -----------------------------------------------------------------------
echo "2. packaged asset matches the repo-root index.html"
if [[ $STATIC_ONLY -eq 1 ]]; then
  meh "not checked (--static)" "run a build to generate $ASSET"
elif [[ ! -f "$ASSET" ]]; then
  meh "$ASSET does not exist yet" "it is generated by :app:copyGameHtml during the build"
elif cmp -s index.html "$ASSET"; then
  ok "byte-identical ($(wc -c < "$ASSET") bytes)"
else
  bad "asset differs from index.html" "$(cmp index.html "$ASSET" 2>&1 | head -1)"
fi

# --- 3 -----------------------------------------------------------------------
echo "3. no INTERNET permission"
manifest_code=$(strip_xml_comments "$MANIFEST")
if grep -qE '<uses-permission[^>]*android\.permission\.INTERNET' <<<"$manifest_code"; then
  bad "INTERNET permission is declared" "$(grep -nE 'android\.permission\.INTERNET' <<<"$manifest_code")"
else
  ok "android.permission.INTERNET absent (not counting the comment that explains why)"
fi

# --- 4 -----------------------------------------------------------------------
echo "4. activity is locked to landscape"
orient=$(grep -oE 'android:screenOrientation="[^"]+"' "$MANIFEST" | head -1 | cut -d'"' -f2)
case "$orient" in
  landscape|sensorLandscape|reverseLandscape|userLandscape)
    ok "screenOrientation=\"$orient\"" ;;
  "") bad "no screenOrientation set in the manifest" ;;
  *)  bad "screenOrientation=\"$orient\" is not a landscape value" ;;
esac

# --- 5 -----------------------------------------------------------------------
# The single most dangerous setting in the project: without it localStorage
# fails inside the WebView and every saved world is lost.
echo "5. WebView enables DOM storage"
activity_code=$(strip_kt_comments "$ACTIVITY")
if grep -qE '(^|[^.[:alnum:]])domStorageEnabled[[:space:]]*=[[:space:]]*true' <<<"$activity_code"; then
  ok "domStorageEnabled = true"
else
  bad "domStorageEnabled is not set to true in $ACTIVITY" \
      "without it localStorage fails and saved worlds are silently lost"
fi

# Same class of risk: a file:// origin would break DOM storage even with the
# setting on, so confirm the page is served through the asset loader.
echo "5b. page is served via WebViewAssetLoader, not file://"
if grep -q 'appassets\.androidplatform\.net' <<<"$activity_code" \
   && ! grep -q 'file:///android_asset' <<<"$activity_code"; then
  ok "loads https://appassets.androidplatform.net/assets/index.html"
else
  bad "the page is not loaded through WebViewAssetLoader" \
      "DOM storage on a file:// origin is unreliable and would break saving"
fi

# --- 6 -----------------------------------------------------------------------
echo "6. the debug APK builds"
if [[ $STATIC_ONLY -eq 1 ]]; then
  meh "not checked (--static)"
elif [[ -f "$APK" ]]; then
  ok "APK present ($(du -h "$APK" | cut -f1)) at $APK"
elif [[ -z "${ANDROID_HOME:-}${ANDROID_SDK_ROOT:-}" ]]; then
  meh "no Android SDK on this machine" "the APK is built by .github/workflows/android.yml"
else
  ( cd android && ./gradlew :app:assembleDebug --no-daemon -q )
  if [[ -f "$APK" ]]; then
    ok "APK built ($(du -h "$APK" | cut -f1))"
  else
    bad "assembleDebug did not produce $APK"
  fi
fi

echo
printf 'passed %d, failed %d, skipped %d\n' "$pass" "$fail" "$skip"
[[ $fail -eq 0 && $skip -eq 0 ]] || exit 1
