#!/usr/bin/env bash
#
# Henrycraft verification checks.
#
#   bash tools/check.sh              run every check
#   bash tools/check.sh --static     skip the two that need an Android build
#
# Checks 2 and 6 need ./gradlew :app:assembleDebug to have produced output, so
# they need the Android SDK. Without it they report SKIP and the script exits
# non-zero, because a skipped check is not a passing one.

set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
ROOT=$(pwd)

STATIC_ONLY=0
[[ "${1:-}" == "--static" ]] && STATIC_ONLY=1

pass=0 fail=0 skip=0

# Colour only when writing to a terminal, so CI logs and the job summary stay
# free of escape codes.
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  C_OK=$'\033[32m'; C_BAD=$'\033[31m'; C_SKIP=$'\033[33m'; C_OFF=$'\033[0m'
else
  C_OK=''; C_BAD=''; C_SKIP=''; C_OFF=''
fi

ok()   { printf '  %sPASS%s  %s\n' "$C_OK" "$C_OFF" "$1"; pass=$((pass+1)); }
bad()  { printf '  %sFAIL%s  %s\n' "$C_BAD" "$C_OFF" "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; fail=$((fail+1)); }
meh()  { printf '  %sSKIP%s  %s\n' "$C_SKIP" "$C_OFF" "$1"; [[ -n "${2:-}" ]] && printf '        %s\n' "$2"; skip=$((skip+1)); }

# Both files below deliberately *document* the things these checks look for -
# the manifest explains the missing INTERNET permission, the Activity explains
# why file:// is not used. Grepping the raw text would match that prose, so
# comments are stripped first and only real code is inspected.
strip_xml_comments() {
  python3 - "$1" <<'PY'
import re, sys
src = open(sys.argv[1], encoding='utf-8').read()
sys.stdout.write(re.sub(r'<!--.*?-->', '', src, flags=re.S))
PY
}

strip_kt_comments() {
  python3 - "$1" <<'PY'
import re, sys
src = open(sys.argv[1], encoding='utf-8').read()
src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)   # block comments and KDoc
src = re.sub(r'(?<!:)//[^\n]*', '', src)          # line comments, but not "https://"
sys.stdout.write(src)
PY
}

APK=android/app/build/outputs/apk/debug/app-debug.apk
ASSET=android/app/src/main/assets/index.html
MANIFEST=android/app/src/main/AndroidManifest.xml
ACTIVITY=android/app/src/main/java/com/flashtech/henrycraft/MainActivity.kt

echo "Henrycraft checks  ($ROOT)"
echo

# --- 1 -----------------------------------------------------------------------
# No external URLs in the page. three.js legitimately contains
# http://www.w3.org/1999/xhtml as the createElementNS namespace, which is not a
# network request, so it is excluded rather than removed.
echo "1. index.html has no external URLs"
urls=$(grep -oE 'https?://[^"'"'"' <>)]+' index.html | grep -v 'www\.w3\.org' | sort -u)
if [[ -z "$urls" ]]; then
  ok "no external URLs (only the w3.org XML namespace remains)"
else
  bad "external URLs found" "$(echo "$urls" | tr '\n' ' ')"
fi

# --- 2 -----------------------------------------------------------------------
echo "2. packaged asset matches the repo-root index.html"
if [[ $STATIC_ONLY -eq 1 ]]; then
  meh "not checked (--static)" "run a build to generate $ASSET"
elif [[ ! -f "$ASSET" ]]; then
  meh "$ASSET does not exist yet" "it is generated by :app:copyGameHtml during the build"
elif cmp -s index.html "$ASSET"; then
  ok "byte-identical ($(wc -c < "$ASSET") bytes)"
else
  bad "asset differs from index.html" "$(cmp index.html "$ASSET" 2>&1 | head -1)"
fi

# --- 3 -----------------------------------------------------------------------
echo "3. no INTERNET permission"
manifest_code=$(strip_xml_comments "$MANIFEST")
if grep -qE '<uses-permission[^>]*android\.permission\.INTERNET' <<<"$manifest_code"; then
  bad "INTERNET permission is declared" "$(grep -nE 'android\.permission\.INTERNET' <<<"$manifest_code")"
else
  ok "android.permission.INTERNET absent (not counting the comment that explains why)"
fi

# --- 4 -----------------------------------------------------------------------
echo "4. activity is locked to landscape"
orient=$(grep -oE 'android:screenOrientation="[^"]+"' "$MANIFEST" | head -1 | cut -d'"' -f2)
case "$orient" in
  landscape|sensorLandscape|reverseLandscape|userLandscape)
    ok "screenOrientation=\"$orient\"" ;;
  "") bad "no screenOrientation set in the manifest" ;;
  *)  bad "screenOrientation=\"$orient\" is not a landscape value" ;;
esac

# --- 5 -----------------------------------------------------------------------
# The single most dangerous setting in the project: without it localStorage
# fails inside the WebView and every saved world is lost.
echo "5. WebView enables DOM storage"
activity_code=$(strip_kt_comments "$ACTIVITY")
if grep -qE '(^|[^.[:alnum:]])domStorageEnabled[[:space:]]*=[[:space:]]*true' <<<"$activity_code"; then
  ok "domStorageEnabled = true"
else
  bad "domStorageEnabled is not set to true in $ACTIVITY" \
      "without it localStorage fails and saved worlds are silently lost"
fi

# Same class of risk: a file:// origin would break DOM storage even with the
# setting on, so confirm the page is served through the asset loader.
echo "5b. page is served via WebViewAssetLoader, not file://"
if grep -q 'appassets\.androidplatform\.net' <<<"$activity_code" \
   && ! grep -q 'file:///android_asset' <<<"$activity_code"; then
  ok "loads https://appassets.androidplatform.net/assets/index.html"
else
  bad "the page is not loaded through WebViewAssetLoader" \
      "DOM storage on a file:// origin is unreliable and would break saving"
fi

# --- 7 -----------------------------------------------------------------------
# The home-screen icon was broken because these were 64x64 data URIs: iOS
# ignores a data-URI apple-touch-icon and draws a letter instead, and with no
# manifest at all Amazon Kids had nothing to use either. Check the real files.
echo "7. home-screen icons and web manifest"
png_size() {
  python3 - "$1" <<'PY'
import struct, sys
with open(sys.argv[1], 'rb') as f:
    head = f.read(24)
if head[:8] != b'\x89PNG\r\n\x1a\n':
    print('notpng'); sys.exit()
w, h = struct.unpack('>II', head[16:24])
print(f'{w}x{h}')
PY
}
icon_fail=0
for spec in "apple-touch-icon.png:180x180" "icon-192.png:192x192" "icon-512.png:512x512"; do
  f=${spec%%:*}; want=${spec##*:}
  if [[ ! -f "$f" ]]; then bad "$f is missing"; icon_fail=1; continue; fi
  got=$(png_size "$f")
  if [[ "$got" == "$want" ]]; then ok "$f is a real PNG at $got"
  else bad "$f is $got, expected $want"; icon_fail=1; fi
done

if grep -q 'rel="apple-touch-icon"[^>]*href="data:' index.html; then
  bad "apple-touch-icon is still a data URI" "iOS ignores these and draws a letter instead"
elif grep -q 'rel="apple-touch-icon"[^>]*href="apple-touch-icon.png"' index.html; then
  ok "apple-touch-icon points at the real 180x180 file"
else
  bad "no apple-touch-icon link pointing at apple-touch-icon.png"
fi

if grep -q 'href="data:image' index.html; then
  bad "index.html still contains a data: URI icon" "$(grep -o 'rel="[a-z-]*"[^>]*href="data:image' index.html | head -2)"
else
  ok "no data: URI icons remain in index.html"
fi

if [[ ! -f manifest.webmanifest ]]; then
  bad "manifest.webmanifest is missing" "Amazon Kids and Android have nothing to read"
else
  man=$(python3 - <<'PY'
import json, sys
try:
    m = json.load(open('manifest.webmanifest', encoding='utf-8'))
except Exception as e:
    print('INVALID ' + str(e)); sys.exit()
missing = [k for k in ('name','short_name','start_url','display','orientation',
                       'background_color','theme_color','icons') if k not in m]
if missing:
    print('MISSING ' + ','.join(missing)); sys.exit()
srcs = sorted(i.get('src','') for i in m['icons'])
if srcs != ['icon-192.png','icon-512.png']:
    print('ICONS ' + ','.join(srcs)); sys.exit()
print(f"OK {m['name']} / {m['short_name']} / {m['display']} / {m['orientation']}")
PY
)
  case "$man" in
    OK*) ok "manifest.webmanifest valid - ${man#OK }" ;;
    *)   bad "manifest.webmanifest problem" "$man" ;;
  esac
fi

# Every icon and the manifest must be a same-origin relative path, so the page
# still works with no network and under the /Henrycraft/ sub-path.
rooted=$(grep -oE '<link[^>]+href="(/|https?://)[^"]*"' index.html || true)
if [[ -z "$rooted" ]]; then
  ok "all icon and manifest links are relative (work under /Henrycraft/ and offline)"
else
  bad "an icon or manifest link is absolute" "$rooted"
fi

# --- 8 -----------------------------------------------------------------------
# GitHub Pages reads CNAME literally. A scheme, a path, a second line or a stray
# space all break the custom domain, and the dashboard reports it as an unhelpful
# "improperly formatted" with the site simply off.
echo "8. CNAME file is well formed"
if [[ ! -f CNAME ]]; then
  meh "no CNAME file" "the site would serve from flashtechusa.github.io instead"
else
  lines=$(grep -c '' CNAME)
  host=$(head -1 CNAME | tr -d '\r')
  if [[ "$lines" -ne 1 ]]; then
    bad "CNAME has $lines lines; it must contain exactly one"
  elif [[ "$host" =~ ^https?:// ]]; then
    bad "CNAME contains a scheme: $host" "it must be a bare hostname"
  elif [[ "$host" == */* ]]; then
    bad "CNAME contains a path: $host" "it must be a bare hostname"
  elif [[ ! "$host" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
    bad "CNAME is not a valid hostname: '$host'"
  else
    ok "CNAME is a single bare hostname: $host"
  fi
fi

# --- 6 -----------------------------------------------------------------------
echo "6. the debug APK builds"
if [[ $STATIC_ONLY -eq 1 ]]; then
  meh "not checked (--static)"
elif [[ -f "$APK" ]]; then
  ok "APK present ($(du -h "$APK" | cut -f1)) at $APK"
elif [[ -z "${ANDROID_HOME:-}${ANDROID_SDK_ROOT:-}" ]]; then
  meh "no Android SDK on this machine" "the APK is built by .github/workflows/android.yml"
else
  ( cd android && ./gradlew :app:assembleDebug --no-daemon -q )
  if [[ -f "$APK" ]]; then
    ok "APK built ($(du -h "$APK" | cut -f1))"
  else
    bad "assembleDebug did not produce $APK"
  fi
fi

echo
printf 'passed %d, failed %d, skipped %d\n' "$pass" "$fail" "$skip"
[[ $fail -eq 0 && $skip -eq 0 ]] || exit 1
